apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-client
  template:
    metadata:
      labels:
        app: mern-client
    spec:
      containers:
      - name: mern-client
        image: vivekchavan14/mern-client
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mern-client
spec:
  selector:
    app: mern-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
