apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-server
  template:
    metadata:
      labels:
        app: mern-server
    spec:
      containers:
      - name: mern-server
        image: vivekchavan14/mern-server
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mern-server
spec:
  selector:
    app: mern-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
